repos:
  - repo: local
    hooks:
      - id: local-pre-commit
        name: local-pre-commit
        entry: .github/hooks/run_hooks.sh "pre-commit"
        language: script
        pass_filenames: false
        verbose: true

      - id: ruff
        name: ruff
        entry: /bin/bash -c "source .venv/bin/activate && ruff check --fix $(git ls-files '*.py')"
        language: script
        pass_filenames: false

      - id: verilator-lint
        name: verilator-lint
        description: Runs verilator to lint System Verilog designs
        entry: .github/hooks/pre-commit/verilator.sh
        language: script
        pass_filenames: false
        verbose: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        exclude: '^(.*\.flac)$'
        args: ['--maxkb=512']
      - id: check-ast
      - id: check-builtin-literals
        args: ['--no-allow-dict-kwargs']
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: mixed-line-ending
        args: ['--fix', 'lf']
      - id: name-tests-test
      - id: pretty-format-json
        args: ['--autofix', '--indent', '4', '--no-ensure-ascii', '--no-sort-keys']
      - id: requirements-txt-fixer

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      name: codespell
      description: Checks for common misspellings in text files.
      entry: .github/hooks/pre-commit/codespell.sh
      language: python
      types: [text]

  - repo: local
    hooks:
      - id: clean-ipynb
        name: clean-ipynb
        entry: .github/hooks/pre-commit/clean_ipynb.sh
        language: script
        pass_filenames: false
        verbose: true
