import numpy as np

from Allocator.Interpreter.polynomial_cse_iccad import optimize_polynomial_iccad


if __name__ == '__main__':
    from math import factorial

    # Example 1: -x^7/7! + x^5/5! - x^3/3! + x. I.e. sin taylor series degree 7
    p_sin_d7 = np.poly1d([
        -1.0/factorial(7), 0.0,
         1.0/factorial(5), 0.0,
        -1.0/factorial(3), 0.0,
         1.0, 0.0
    ])
    code, stats = optimize_polynomial_iccad(p_sin_d7)
    print(code)
    print(stats)

    # Example 2: sin taylor series degree 9
    p_sin_d9 = np.poly1d([
        1.0/factorial(9), 0.0,
        -1.0/factorial(7), 0.0,
         1.0/factorial(5), 0.0,
        -1.0/factorial(3), 0.0,
         1.0, 0.0
    ])
    code2, stats2 = optimize_polynomial_iccad(p_sin_d9)
    print(code2)
    print(stats2)

    # Example 3: sqrt(x + 1) taylor series degree 3
    p_sqrt_d3 = np.poly1d([
        1/16, -1/8, 1/2, 1
    ])
    code3, stats3 = optimize_polynomial_iccad(p_sqrt_d3)
    print(code3)
    print(stats3)

    # Example 4: cos(x) taylor series degree 6
    p_cos_d6 = np.poly1d([
        -1.0/factorial(6), 0.0,
        1.0/factorial(4), 0.0,
         -1.0/2, 0.0,
         1.0
    ])
    code4, stats4 = optimize_polynomial_iccad(p_cos_d6)
    print(code4)
    print(stats4)

    # The outputs below were automatically generated by the above ^^^


    def optimized_polynomial_sin_deg7(x: np.floating,
                                      coefs: np.ndarray[np.floating | np.integer]) -> np.floating:
        coefs = np.abs(coefs)
        d1 = x*x
        d3 = coefs[0]*d1 + coefs[2]
        d4 = d3*d1 - coefs[4]
        d5 = d4*d1 + coefs[6]
        y = x*d5
        return y


    def optimized_polynomial_sin_deg9(x: np.floating,
                                      coefs: np.ndarray[np.floating | np.integer]) -> np.floating:
        coefs = np.abs(coefs)
        d1 = x*x
        d3 = coefs[0]*d1 - coefs[2]
        d4 = d3*d1 + coefs[4]
        d5 = d4*d1 - coefs[6]
        d6 = d5*d1 + coefs[8]
        y = x*d6
        return y


    def optimized_polynomial_sqrtx1_deg3(x: np.floating,
                                         coefs: np.ndarray[np.floating | np.integer]) -> np.floating:
        coefs = np.abs(coefs)
        d1 = x*x
        d3 = coefs[0]*d1 + coefs[2]
        d5 = -coefs[1]*d1 + coefs[3]
        y = d5 + x*d3
        return y


    def optimized_polynomial_cos_deg6(x: np.floating, coefs: np.ndarray[np.floating | np.integer]) -> np.floating:
        coefs = np.abs(coefs)
        d1 = x*x
        d3 = -coefs[0]*d1 + coefs[2]
        d4 = d3*d1 - coefs[4]
        d5 = d4*d1 + coefs[6]
        y = d5
        return y


    print(optimized_polynomial_sin_deg7(np.pi / 4, p_sin_d7))
    print(optimized_polynomial_sin_deg9(np.pi / 4, p_sin_d9))
    print(optimized_polynomial_sin_deg7(0, p_sin_d7))
    print(optimized_polynomial_cos_deg6(np.pi / 4, p_cos_d6))
    print(optimized_polynomial_cos_deg6(0, p_cos_d6))
    print(optimized_polynomial_sqrtx1_deg3(-0.5, p_sqrt_d3))
