"""
------------------------------------------------------------------------
Filename: 	bitfield.py

Project:	LLAC, intelligent hardware scheduler targeting common audio signal chains.

For more information see the repository: https://github.com/topologicalhurt/Thesis

Purpose:	N/A

Author: topologicalhurt csin0659@uni.sydney.edu.au

------------------------------------------------------------------------
Copyright (C) 2025, LLAC project LLC

This file is a part of the ALLOCATOR module
It is intended to be used as part of the allocator design which is responsible for the soft-core, or offboard, management of the on-fabric components.
Please refer to docs/whitepaper first, which provides a complete description of the project & it's motivations.

The design is NOT COVERED UNDER ANY WARRANTY.

LICENSE:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
As defined by GNU GPL 3.0 https://www.gnu.org/licenses/gpl-3.0.html

A copy of this license is included at the root directory. It should've been provided to you
Otherwise please consult: https://github.com/topologicalhurt/Thesis/blob/main/LICENSE
------------------------------------------------------------------------
"""

import importlib
import numpy as np

from enum import Enum,  _EnumDict
from collections.abc import Iterable, Mapping, Set
from typing import Any

from Allocator.Interpreter.extendedenum import ExtendedEnum, _ExtendedEnumMeta


helpers = importlib.import_module('.helpers', 'Allocator.Interpreter')
nptypes = importlib.import_module('.nptypes', 'Allocator.Interpreter')
combined_fast_stable_hash = helpers.combined_fast_stable_hash
find_left_shift_from_integer_offset = helpers.find_left_shift_from_integer_offset
find_left_shift_from_iterable_offset = helpers. find_left_shift_from_iterable_offset


class _BitFieldEnumMeta(_ExtendedEnumMeta):
    """# Summary

    Metaclass for creating Enum types where member values are generated by
    left-shifting an initial integer value by the member's order index.
    """

    def get_bit_str(self) -> int:
        return sum(list(map(lambda c: c.value, self)))

    @classmethod
    def _get_allowed_names(mcs, allowed_spec: Any | None) -> Set:
        """ # Summary

        Format the allowed spec into a set

        ## Args:
            mcs: _description_ Aliases __new__
            allowed_spec: _description_ The whitelisted attribute names to format

        ## Returns:
            _Set_: _description_ The set wrapped version of allowed_spec
        """
        if allowed_spec is None:
            return None
        if isinstance(allowed_spec, Enum):
            return set(allowed_spec.value)
        if isinstance(allowed_spec, Mapping):
            return set(allowed_spec.keys())
        if isinstance(allowed_spec, Iterable):
            return set(allowed_spec)

    @classmethod
    def _process_member_defs(mcs, allowed_names: Iterable[str] | None,
                             offset: Iterable[np.uint] | np.uint,
                             clsdict: Mapping,
                             count: bool = True,
                             in_first_msb: bool = True,
                             **kwargs) -> None:
        """# Summary

        Iterate through keyword arguments provided at class definition, preserving their order (Python 3.7+).
        Store the attributes as part of the enums class dictionary.

        ## Args:
            mcs (_type_): _description_ Aliases __new__
            allowed_names (_type_): _description_ The whitelisted attribute names. If None then
            offset: The amount to begin left shifting at
            clsdict (_type_): _description_ Aliases __new__ (enum's class dict)
            count: determines whether to index or just use raw offset
            in_first_msb (bool, optional): _description_ determines if the first bit is the MSB. Defaults to True.
        """
        if allowed_names is not None:
            for k in kwargs:
                k = str.upper(k)
                if k not in allowed_names:
                    raise NameError(
                        f'Member name "{k}" is not allowed for class "{mcs.__name__}". '
                        f'Permitted members are: {sorted(list(allowed_names))}.'
                    )

        kwargs_items = kwargs.items()
        offset_is_iterable = isinstance(offset, Iterable)
        args_length = len(kwargs) - 1

        i = 0 # Index counting # of args if count is set
        j = 0 # Index counting into offset if offset is an iterable
        for member_name, initial_value in kwargs_items:
            if not isinstance(initial_value, int):
                raise TypeError(
                    f'Value for enum member "{member_name}" must be an integer '
                    f'for bitwise shift, got {type(initial_value).__name__}.'
                )

            if member_name in clsdict:
                raise NameError(
                    f'Enum member name "{member_name}" from keyword arguments '
                    f'conflicts with an item ("{clsdict[member_name]}") already defined in the class body.'
                )

            if offset_is_iterable:
                leftshift = find_left_shift_from_iterable_offset(offset, j, i, in_first_msb=in_first_msb)
                j += 1
            else:
                leftshift = find_left_shift_from_integer_offset(offset, args_length, i, in_first_msb=in_first_msb)

            if count:
                i += 1

            result = nptypes.STANDARD_NP_DTYPES.LARGEST_UINT.value(initial_value << leftshift)
            clsdict[member_name] = result

    def __str__(self):
        return str(list(map(lambda c: c.value, self)))

    def __new__(mcs, name, bases, clsdict, **kwargs):
        """ ## Summary

        Overrides __new__ class from the enum metaclass. Allows for an enum
        inheriting from BitFieldEnumMeta to concretize it's attributes in
        the class definition, instead of at instantiation in the constructor
        (ala __call__.)
        """
        allowed_spec = clsdict.get('ALLOWED', None)
        allowed_names = mcs._get_allowed_names(allowed_spec)
        mcs._process_member_defs(
            allowed_names=allowed_names,
            offset=0,
            clsdict=clsdict,
            count=True,
            **kwargs
        )
        return super().__new__(mcs, name, bases, clsdict, **kwargs)

    def __call__(cls, offset: Iterable[int] | int = 0, count: bool = True, *args, **kwargs):
        """ # Summary

        Overrides the __call__ method of the Enum parent class. I.e. the metaclasses
        enum factory. Names the returned class based on a hash of the key attributes.

        ## Returns:
            _Enum_: _description_ An enum class instance
        """
        if not args and kwargs:
            dynamic_members = _EnumDict()
            allowed_spec = getattr(cls, 'ALLOWED', None)
            allowed_names = cls._get_allowed_names(allowed_spec)
            cls._process_member_defs(
                allowed_names=allowed_names,
                offset=offset,
                clsdict=dynamic_members,
                count=count,
                **kwargs
            )

            # Enum factory based on hash of attributes (kwargs)
            # Should be good enough to not create conflicting alias within namespace
            member_items_for_hash = [key.encode('utf-8') for key in kwargs]
            hsh = hex(combined_fast_stable_hash(member_items_for_hash))
            dynamic_name = f'{cls.__name__}_{hsh}'

            new_enum_class = cls.__class__(dynamic_name, (cls,), dynamic_members)
            return new_enum_class

        raise TypeError(
            f'{cls.__name__}() called without keyword arguments. '
                'Use keyword arguments only for dynamic enum creation.'
        )


class BITFIELD(ExtendedEnum, metaclass=_BitFieldEnumMeta):
    """# Summary

    Base class for Enums where members are defined via keyword arguments
    to the class definition. The value of each member is the
    provided integer value, LEFT-shifted by its order (index).

    ## Example:
        class MyFlags(OrderedShiftedEnum, F1=1, F2=1, F3=1):
            pass

        MyFlags.F1.value will be 1 (1 << 0)

        MyFlags.F2.value will be 2 (1 << 1)

        MyFlags.F3.value will be 4 (1 << 2)
    """
    @classmethod
    def list(cls):
        return list(map(lambda c: c.value, cls))
