"""
------------------------------------------------------------------------
Filename: 	bitfield.py

Project:	LLAC, intelligent hardware scheduler targeting common audio signal chains.

For more information see the repository: https://github.com/topologicalhurt/Thesis

Purpose:	N/A

Author: topologicalhurt csin0659@uni.sydney.edu.au

------------------------------------------------------------------------
Copyright (C) 2025, LLAC project LLC

This file is a part of the ALLOCATOR module
It is intended to be used as part of the allocator design which is responsible for the soft-core, or offboard, management of the on-fabric components.
Please refer to docs/whitepaper first, which provides a complete description of the project & it's motivations.

The design is NOT COVERED UNDER ANY WARRANTY.

LICENSE:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
As defined by GNU GPL 3.0 https://www.gnu.org/licenses/gpl-3.0.html

A copy of this license is included at the root directory. It should've been provided to you
Otherwise please consult: https://github.com/topologicalhurt/Thesis/blob/main/LICENSE
------------------------------------------------------------------------
"""

import numpy as np

from enum import Enum, _EnumDict
from collections.abc import Generator, Hashable, Iterable, Mapping, Set
from typing import Any, override

from Allocator.Interpreter.helpers import combined_fast_stable_hash
from Allocator.Interpreter.nptypes import STANDARD_NP_DTYPES
from Allocator.Interpreter.extendedenum import ExtendedEnum, _ExtendedEnumMeta


class BitFieldEnumMeta(_ExtendedEnumMeta):
    """# Summary

    Metaclass for creating Enum types where member values are generated by
    left-shifting an initial integer value by the member's order index.
    """

    @staticmethod
    def _compute_positions(n: int,
                           offset: Iterable[int] | int = 0,
                           count: bool = True,
                           msb_first: bool = True) -> list[int]:
        """Compute absolute bit positions for n flags.

        - If offset is an int: positions are offset + i when count=True, else [offset]*n.
        - If offset is an iterable: positions are offset[i] + i when count=True, else offset[i].
        - If msb_first=True, positions are mirrored so that the first name maps to the highest bit.
        """
        if isinstance(offset, Iterable) and not isinstance(offset, (bytes, bytearray, str)):
            offs = list(offset)
            if len(offs) < n:
                raise ValueError(f'Offset iterable must have at least {n} elements, got {len(offs)}')
            base_positions = [int(offs[i]) + (i if count else 0) for i in range(n)]
        else:
            base = int(offset) if isinstance(offset, (int, np.integer)) else 0
            base_positions = [base + (i if count else 0) for i in range(n)]

        if not base_positions:
            return []

        # For msb_first, map the first provided name to the highest absolute position.
        # Preserve absolute positions to avoid aliasing/dropping fields.
        if msb_first:
            ordered = sorted(base_positions, reverse=True)
            return ordered
        return base_positions

    @staticmethod
    def bools2bitstr(*args: bool,
                     msb_first: bool = True,
                     offset: Iterable[int] | int = 0,
                     count: bool = True) -> np.uint:
        """Pack a sequence of booleans into an integer bitfield using absolute positions.

        Each True in args sets a bit at the computed position; False leaves it clear.
        See _compute_positions for semantics of offset/count/msb_first.
        """
        positions = BitFieldEnumMeta._compute_positions(len(args), offset=offset, count=count, msb_first=msb_first)
        result = 0
        for flag, pos in zip(args, positions):
            if flag:
                result |= (1 << int(pos))
        return STANDARD_NP_DTYPES.LARGEST_UINT.value(result)

    @staticmethod
    def _get_allowed_names(allowed_spec: Any | None) -> Set:
        """ # Summary

        Format the allowed spec into a set

        ## Args:
            allowed_spec: _description_ The whitelisted attribute names to format

        ## Returns:
            _Set_: _description_ The set wrapped version of allowed_spec
        """
        if allowed_spec is None:
            return None
        if isinstance(allowed_spec, Enum):
            return set(allowed_spec.value)
        if isinstance(allowed_spec, dict):
            return set(allowed_spec.keys())
        if isinstance(allowed_spec, (list, tuple)):
            return set(allowed_spec)

    @staticmethod
    def enumerate_bit_positions_from_val(val: np.uint,
                                         msb_first: bool = True) -> Generator[int]:
        """Enumerate bit indices set to 1 in `val` up to `bit_length` bits."""
        val_int = int(val)
        if msb_first:
            rng = range(int(val_int.bit_length()) - 1, -1, -1)
        else:
            rng = range(int(val_int.bit_length()))

        for i in rng:
            if val & (1 << i):
                yield i

    def enumerate_bit_positions(self, msb_first: bool = True) -> Generator[int]:
        """Enumerate the bit positions set to 1 in the bit field."""
        return BitFieldEnumMeta.enumerate_bit_positions_from_val(self.int_sig,
                                                                 msb_first=msb_first)

    @classmethod
    def _member_factory(cls,
                        allowed_names: Iterable[str] | None,
                        offset: Iterable[int] | int,
                        clsdict: Mapping,
                        count: bool = True,
                        msb_first: bool = True,
                        **kwargs) -> tuple[dict[str, int], int, int]:
        """# Summary

        Iterate through keyword arguments provided at class definition, preserving their order (Python 3.7+).
        Store the attributes as part of the enums class dictionary.

        ## Args:
            mcs (_type_): _description_ Aliases __new__
            allowed_names (_type_): _description_ The whitelisted attribute names. If None then
            offset: The amount to begin left shifting at
            clsdict (_type_): _description_ Aliases __new__ (enum's class dict)
            count: determines whether to index or just use raw offset
            in_first_msb (bool, optional): _description_ determines if the first bit is the MSB. Defaults to True.
        """
        if allowed_names is not None:
            for k in kwargs:
                k_up = str.upper(k)
                if k_up not in allowed_names:
                    raise NameError(
                        f'Member name "{k_up}" is not allowed for class "{cls.__name__}". '
                        f'Permitted members are: {sorted(list(allowed_names))}.'
                    )

        for member_name, initial_value in kwargs.items():
            if not isinstance(initial_value, int):
                raise TypeError(
                    f'Value for enum member "{member_name}" must be an integer '
                    f'for bitwise shift, got {type(initial_value).__name__}.'
                )

            if initial_value < 0:
                raise ValueError(
                    f'Value for enum member "{member_name}" must be non-negative, got {initial_value}.'
                )

            if member_name in clsdict:
                raise NameError(
                    f'Enum member name "{member_name}" from keyword arguments '
                    f'conflicts with an item ("{clsdict[member_name]}") already defined in the class body.'
                )

        # Compute absolute positions (one per member, ordered by kwargs order)
        names = list(kwargs.keys())
        base_offsets = list(kwargs.values())
        bit_length = len(names)

        # Combine provided `offset` and per-member `base_offsets`
        if isinstance(offset, Iterable) and not isinstance(offset, (bytes, bytearray, str)):
            if len(offset) < bit_length:
                raise ValueError(f'Offset iterable must have at least {bit_length} elements, got {len(offset)}')
            combined = [int(o) + int(b) for o, b in zip(offset, base_offsets)]
        else:
            combined = [int(offset) + int(b) for b in base_offsets]

        positions = cls._compute_positions(bit_length, offset=combined, count=count, msb_first=msb_first)
        dynamic_members: dict[str, int] = {}
        int_sig = 0
        for name, pos in zip(names, positions):
            mask = 1 << pos
            dynamic_members[name] = mask
            int_sig |= mask

        return dynamic_members, int(bit_length), int(int_sig)

    def list(self):
        return [m.value for m in self]

    def __str__(self):
        return f'{self.__name__}({', '.join(f'{m.name}={m.value}' for m in self.get_members())})'

    @property
    def sig(self) -> np.uint:
        """Class-level signature of the bitfield (OR of member masks)."""
        return getattr(self, 'int_sig', STANDARD_NP_DTYPES.LARGEST_UINT.value(0))

    @property
    def n_bits(self) -> np.uint32:
        """Class-level bit-length (number of positions)."""
        return getattr(self, 'bit_length', np.uint32(0))

    def __hash__(self):
        return getattr(self, '_hsh_sig', 0)

    def __eq__(self, other):
        if not isinstance(other, Hashable):
            raise TypeError('Object in equality expression must be hashable')
        return hash(self) == hash(other)

    def __iter__(self):
        for field, value, pos in zip(self.fields(), self.values(), self.enumerate_bit_positions()):
            yield field, value, pos

    def __call__(cls, offset: Iterable[int] | int = 0, count: bool = True, msb_first: bool = True,
                 *args, **kwargs):
        """ # Summary

        Overrides the __call__ method of the Enum parent class. I.e. the metaclasses
        enum factory. Names the returned class based on a hash of the key attributes.

        ## Returns:
            _Enum_: _description_ An enum class instance
        """
        if not args and kwargs:
            dynamic_members = _EnumDict()
            allowed_spec = getattr(cls, 'ALLOWED', None)
            allowed_names = cls._get_allowed_names(allowed_spec)
            members_map, bit_length, int_sig = cls._member_factory(
                allowed_names=allowed_names,
                offset=offset,
                clsdict=dynamic_members,
                count=count,
                msb_first=msb_first,
                **kwargs
            )
            # Populate the enum dict with computed masks
            for k, v in members_map.items():
                dynamic_members[k] = v

            """ Enum factory based on stable hash of (name, computed mask) pairs
            Use deterministic bytes to avoid Python's salted hash instability
            Also, in-sensitive to order I.e. member position doesn't matter """
            members = {k: v for k, v in sorted(kwargs.items(), key=lambda item: item[1])}
            member_items_digestable: list[bytes] = []
            for name in members:
                mask = int(members_map[name])
                name_b = name.encode('utf-8')
                nbytes = max(1, (mask.bit_length() + 7) // 8)
                mask_b = mask.to_bytes(nbytes, byteorder='big', signed=False)
                member_items_digestable.append(name_b)
                member_items_digestable.append(mask_b)

            hsh = combined_fast_stable_hash(member_items_digestable)
            dynamic_name = f'{cls.__name__}_{hsh:X}'
            new_cls = cls.__class__(dynamic_name, (cls,), dynamic_members)

            # Attach metadata to the newly created class
            setattr(new_cls, 'bit_length', np.uint32(bit_length))
            setattr(new_cls, 'int_sig', STANDARD_NP_DTYPES.LARGEST_UINT.value(int_sig))
            setattr(new_cls, '_hsh_sig', hsh)

            return new_cls

        raise TypeError(f'{cls.__name__}() called without keyword arguments. '
                        'Use keyword arguments only for dynamic enum creation.'
                        )


class BITFIELD(ExtendedEnum, metaclass=BitFieldEnumMeta):
    """# Summary

    Base class for Enums where members are defined via keyword arguments
    to the class definition. The value of each member is the
    provided integer value, LEFT-shifted by its order (index).

    ## Example:
        class MyFlags(OrderedShiftedEnum, F1=1, F2=1, F3=1):
            pass

        MyFlags.F1.value will be 1 (1 << 0)

        MyFlags.F2.value will be 2 (1 << 1)

        MyFlags.F3.value will be 4 (1 << 2)
    """
    @override
    @classmethod
    def fields(cls) -> Iterable:
        return list(cls.__members__.keys())

    @override
    @classmethod
    def values(cls) -> Iterable:
        return list([v.value for v in cls.__members__.values()])

    @classmethod
    def bitfield_from_enum_mask(cls, e: ExtendedEnum, mask: Iterable[str] | None,
                                msb_first: bool = True):
        members = e.get_members_from_mask(mask)
        positions: list[int] = []
        for m in members:
            v = int(m.value)
            if v > 0 and (v & (v - 1)) == 0:
                positions.append(v.bit_length() - 1)
            else:
                positions.append(v)
        return cls.__call__(offset=positions, count=False, msb_first=msb_first,
                            **{m.name: 0 for m in members})

    @staticmethod
    def bitstr_from_enum_mask(e: ExtendedEnum, mask: Iterable[str] | None,  msb_first: bool = True, *args: bool) -> int:
        members = e.get_members_from_mask(mask)
        # Interpret member values: if they are single-bit masks (power of two),
        # convert to the bit index; otherwise treat the value as the absolute bit index.
        positions: list[int] = []
        for m in members:
            v = int(m.value)
            if v > 0 and (v & (v - 1)) == 0:
                # single-bit mask -> bit position
                positions.append(v.bit_length() - 1)
            else:
                positions.append(v)
        if not args:
            args = [True] * len(positions)
        return BitFieldEnumMeta.bools2bitstr(*args, offset=positions, count=False, msb_first=msb_first)
