"""
------------------------------------------------------------------------
Filename: 	bitfield.py

Project:	LLAC, intelligent hardware scheduler targeting common audio signal chains.

For more information see the repository: https://github.com/topologicalhurt/Thesis

Purpose:	N/A

Author: topologicalhurt csin0659@uni.sydney.edu.au

------------------------------------------------------------------------
Copyright (C) 2025, LLAC project LLC

This file is a part of the ALLOCATOR module
It is intended to be used as part of the allocator design which is responsible for the soft-core, or offboard, management of the on-fabric components.
Please refer to docs/whitepaper first, which provides a complete description of the project & it's motivations.

The design is NOT COVERED UNDER ANY WARRANTY.

LICENSE:     GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
As defined by GNU GPL 3.0 https://www.gnu.org/licenses/gpl-3.0.html

A copy of this license is included at the root directory. It should've been provided to you
Otherwise please consult: https://github.com/topologicalhurt/Thesis/blob/main/LICENSE
------------------------------------------------------------------------
"""

import numpy as np

from enum import Enum, _EnumDict
from collections.abc import Generator, Hashable, Iterable, Mapping, Set
from typing import Any, override

from Allocator.Interpreter.main.util_helpers import combined_fast_stable_hash
from Allocator.Interpreter.main.extendedenum import ExtendedEnum, _ExtendedEnumMeta
from Allocator.Interpreter.math.nptypes import STANDARD_NP_DTYPES


class BitFieldEnumMeta(_ExtendedEnumMeta):
    """# Summary

    Metaclass for creating Enum types where member values are generated by
    left-shifting an initial integer value by the member's order index.
    """
    __slots__ = ()

    @staticmethod
    def _compute_positions(n: int,
                           offset: Iterable[int] | int = 0,
                           count: bool = True,
                           msb_first: bool = True,
                           preserve_order_for_iterable: bool = True) -> list[int]:
        """Compute absolute bit positions for n flags.

        - If offset is an int: positions are offset + i when count=True, else [offset]*n.
        - If offset is an iterable: positions are offset[i] + i when count=True, else offset[i].
        - If msb_first=True, positions are mirrored so that the first name maps to the highest bit.
        """
        if isinstance(offset, Iterable) and not isinstance(offset, (bytes, bytearray, str)):
            offs = list(offset)
            if len(offs) < n:
                raise ValueError(f'Offset iterable must have at least {n} elements, got {len(offs)}')
            base_positions = [int(offs[i]) + (i if count else 0) for i in range(n)]
        else:
            base = int(offset) if isinstance(offset, (int, np.integer)) else 0
            base_positions = [base + (i if count else 0) for i in range(n)]

        if not base_positions:
            return []

        # If explicit absolute positions are provided by the user (offset iterable) and count=False,
        # optionally preserve that exact ordering regardless of msb_first. This preserves semantics
        # for explicit iterable offsets like offset=[...]. When offset originated from a scalar
        # (i.e., internally expanded), preserve_order_for_iterable should be False so msb_first applies.
        if (
            preserve_order_for_iterable
            and isinstance(offset, Iterable)
            and not isinstance(offset, (bytes, bytearray, str))
            and not count
        ):
            return base_positions

        # Otherwise, for msb_first, map the first provided name to the highest absolute position.
        if msb_first:
            return sorted(base_positions, reverse=True)
        return base_positions

    @staticmethod
    def bools2bitstr(*args: bool,
                     msb_first: bool = True,
                     offset: Iterable[int] | int = 0,
                     count: bool = True) -> np.uint:
        """Pack a sequence of booleans into an integer bitfield using absolute positions.

        Each True in args sets a bit at the computed position; False leaves it clear.
        See _compute_positions for semantics of offset/count/msb_first.
        """
        positions = BitFieldEnumMeta._compute_positions(len(args), offset=offset, count=count, msb_first=msb_first,
                                                        preserve_order_for_iterable=True
                                                        )
        result = 0
        for flag, pos in zip(args, positions):
            if flag:
                result |= (1 << int(pos))
        return STANDARD_NP_DTYPES.LARGEST_UINT.value(result)

    @staticmethod
    def _get_allowed_names(allowed_spec: Any | None) -> Set:
        """ # Summary

        Format the allowed spec into a set

        ## Args:
            allowed_spec: _description_ The whitelisted attribute names to format

        ## Returns:
            _Set_: _description_ The set wrapped version of allowed_spec
        """
        if allowed_spec is None:
            return None
        if isinstance(allowed_spec, Enum):
            return set(allowed_spec.value)
        if isinstance(allowed_spec, dict):
            return set(allowed_spec.keys())
        if isinstance(allowed_spec, (list, tuple)):
            return set(allowed_spec)

    @staticmethod
    def enumerate_bit_positions_from_val(val: np.uint,
                                         msb_first: bool = True) -> Generator[int]:
        """Enumerate bit indices set to 1 in `val` up to `bit_length` bits."""
        val_int = int(val)
        if msb_first:
            rng = range(int(val_int.bit_length()) - 1, -1, -1)
        else:
            rng = range(int(val_int.bit_length()))

        for i in rng:
            if val & (1 << i):
                yield i

    @staticmethod
    def _positions_from_enum_mask(members: list[Enum]) -> list[int]:
        """Return absolute bit positions for members from an enum subset.

        If member values are single-bit masks, convert to bit indices; otherwise treat
        values as absolute positions.
        """
        vals = [int(m.value) for m in members]
        if not vals:
            return []
        are_masks = all(v > 0 and (v & (v - 1)) == 0 for v in vals)
        if are_masks:
            return [int(v).bit_length() - 1 for v in vals]
        return vals

    @staticmethod
    def bitstr_from_enum_mask(*args: bool, **kwargs) -> int:
        """Build a bitstring from an enum mask and optional flag booleans.

        Supports both call styles:
        - Positional-first: bitstr_from_enum_mask(e, mask, msb_first=True, *flags)
        - Keyword-first with star expansion: bitstr_from_enum_mask(*flags, e=..., mask=..., msb_first=True)
        """
        # Disambiguate arguments
        if 'e' in kwargs:
            e = kwargs.pop('e')
            mask = kwargs.pop('mask', None)
            msb_first = kwargs.pop('msb_first', True)
            flags = list(args)
        else:
            if len(args) < 2:
                raise TypeError('bitstr_from_enum_mask expected at least (e, mask), got fewer positional args')

            e = args[0]
            mask = args[1]

            if len(args) >= 3 and isinstance(args[2], (bool, np.bool_)):
                msb_first = bool(args[2])
                flags = list(args[3:])
            else:
                msb_first = True
                flags = list(args[2:])

        members = e.get_members_from_mask(mask)
        if not flags:
            flags = [True] * len(members)

        # Determine if enum values are masks (single-bit) or absolute positions
        vals = [int(m.value) for m in members]
        are_masks = len(vals) > 0 and all(v > 0 and (v & (v - 1)) == 0 for v in vals)

        # Compute positions for ordering, then choose index order
        positions = [int(v).bit_length() - 1 for v in vals] if are_masks else vals
        if isinstance(mask, (list, tuple)):
            order = range(len(members))
        else:
            order = sorted(range(len(members)), key=lambda i: positions[i], reverse=bool(msb_first))

        # Build bitstring by aligning flags to the chosen order
        result = 0
        for flag, idx in zip(flags, order):
            if not flag:
                continue

            v = vals[idx]
            if are_masks:
                result |= v
                continue
            result |= (1 << int(v))

        return STANDARD_NP_DTYPES.LARGEST_UINT.value(result)


    def bitfield_from_enum_mask(self, *args, **kwargs):
        """Create a BITFIELD subclass from an enum and an optional name mask.

        Supports both call styles:
        - Positional-first: bitfield_from_enum_mask(e, mask=None, msb_first=True)
        - Keyword-first: bitfield_from_enum_mask(e=..., mask=..., msb_first=True)
        """
        if 'e' in kwargs:
            e = kwargs.pop('e')
            mask = kwargs.pop('mask', None)
            msb_first = kwargs.pop('msb_first', True)
        else:
            if len(args) < 1:
                raise TypeError('bitfield_from_enum_mask expected at least (e,), got fewer positional args')

            e = args[0]
            mask = args[1] if len(args) >= 2 else None
            if len(args) >= 3 and isinstance(args[2], (bool, np.bool_)):
                msb_first = bool(args[2])
            else:
                msb_first = True

        members = e.get_members_from_mask(mask)
        positions = BitFieldEnumMeta._positions_from_enum_mask(members)
        return self.__call__(offset=positions, count=False, msb_first=msb_first,
                             **{m.name: 0 for m in members})

    @classmethod
    def _member_factory(cls,
                        allowed_names: Iterable[str] | None,
                        offset: Iterable[int] | int,
                        clsdict: Mapping,
                        count: bool = True,
                        msb_first: bool = True,
                        **kwargs) -> tuple[dict[str, int], int, int]:
        """Validate and construct dynamic enum members and metadata.

        Returns a tuple: (members_map, bit_length, int_sig)
        """
        if allowed_names is not None:
            for k in kwargs:
                k_up = str.upper(k)
                if k_up not in allowed_names:
                    raise NameError(
                        f'Member name "{k_up}" is not allowed for class "{cls.__name__}". '
                        f'Permitted members are: {sorted(list(allowed_names))}.'
                    )

        for member_name, initial_value in kwargs.items():
            if not isinstance(initial_value, int):
                raise TypeError(
                    f'Value for enum member "{member_name}" must be an integer '
                    f'for bitwise shift, got {type(initial_value).__name__}.'
                )
            if initial_value < 0:
                raise ValueError(
                    f'Value for enum member "{member_name}" must be non-negative, got {initial_value}.'
                )
            if member_name in clsdict:
                raise NameError(
                    f'Enum member name "{member_name}" from keyword arguments '
                    f'conflicts with an item ("{clsdict[member_name]}") already defined in the class body.'
                )

        names = list(kwargs.keys())
        base_offsets = list(kwargs.values())
        bit_length = len(names)

        if isinstance(offset, Iterable) and not isinstance(offset, (bytes, bytearray, str)):
            if len(offset) < bit_length:
                raise ValueError(f'Offset iterable must have at least {bit_length} elements, got {len(offset)}')
            combined = [int(o) + int(b) for o, b in zip(offset, base_offsets)]
        else:
            combined = [int(offset) + int(b) for b in base_offsets]

        # Preserve explicit iterable offset ordering only if the user provided an iterable offset.
        provided_iterable_offset = isinstance(offset, Iterable) and not isinstance(offset, (bytes, bytearray, str))
        positions = cls._compute_positions(
            bit_length,
            offset=combined,
            count=count,
            msb_first=msb_first,
            preserve_order_for_iterable=provided_iterable_offset,
        )
        dynamic_members: dict[str, int] = {}
        int_sig = 0
        for name, pos in zip(names, positions):
            mask = 1 << pos
            dynamic_members[name] = mask
            int_sig |= mask

        return dynamic_members, int(bit_length), int(int_sig)

    def enumerate_bit_positions(self, msb_first: bool = True) -> Generator[int]:
        """Enumerate the bit positions set to 1 in the bit field."""
        return BitFieldEnumMeta.enumerate_bit_positions_from_val(self.int_sig,
                                                                 msb_first=msb_first)

    def list(self):
        return [m.value for m in self]

    def __str__(self):
        parts = []
        for m in self.get_members():
            parts.append(f"{m.name}={m.value}")
        return f"{self.__name__}({', '.join(parts)})"

    @property
    def sig(self) -> np.uint:
        """Class-level signature of the bitfield (OR of member masks)."""
        return getattr(self, 'int_sig', STANDARD_NP_DTYPES.LARGEST_UINT.value(0))

    @property
    def n_bits(self) -> np.uint32:
        """Class-level bit-length (number of positions)."""
        return getattr(self, 'bit_length', np.uint32(0))

    def __hash__(self):
        return getattr(self, '_hsh_sig', 0)

    def __eq__(self, other):
        if not isinstance(other, Hashable):
            raise TypeError('Object in equality expression must be hashable')
        return hash(self) == hash(other)

    def __iter__(self):
        yield from zip(self.fields(), self.values(), self.enumerate_bit_positions())

    def __call__(cls, offset: Iterable[int] | int = 0, count: bool = True, msb_first: bool = True,
                 *args, **kwargs):
        """ # Summary

        Overrides the __call__ method of the Enum parent class. I.e. the metaclasses
        enum factory. Names the returned class based on a hash of the key attributes.

        ## Returns:
            _Enum_: _description_ An enum class instance
        """
        if not args and kwargs:
            dynamic_members = _EnumDict()
            allowed_spec = getattr(cls, 'ALLOWED', None)
            allowed_names = cls._get_allowed_names(allowed_spec)
            members_map, bit_length, int_sig = cls._member_factory(
                allowed_names=allowed_names,
                offset=offset,
                clsdict=dynamic_members,
                count=count,
                msb_first=msb_first,
                **kwargs
            )

            # Populate the enum dict with computed masks
            for k, v in members_map.items():
                dynamic_members[k] = v

            """ Enum factory based on stable hash of (name, computed mask) pairs
            Use deterministic bytes to avoid Python's salted hash instability
            Also, in-sensitive to order I.e. member position doesn't matter """
            members = {k: v for k, v in sorted(kwargs.items(), key=lambda item: item[1])}
            member_items_digestable: list[bytes] = []
            for name in members:
                mask = int(members_map[name])
                name_b = name.encode('utf-8')
                nbytes = max(1, (mask.bit_length() + 7) // 8)
                mask_b = mask.to_bytes(nbytes, byteorder='big', signed=False)
                member_items_digestable.append(name_b)
                member_items_digestable.append(mask_b)

            hsh = combined_fast_stable_hash(member_items_digestable)
            dynamic_name = f'{cls.__name__}_{hsh:X}'
            new_cls = cls.__class__(dynamic_name, (cls,), dynamic_members)

            # Attach metadata to the newly created class
            setattr(new_cls, 'bit_length', np.uint32(bit_length))
            setattr(new_cls, 'int_sig', STANDARD_NP_DTYPES.LARGEST_UINT.value(int_sig))
            setattr(new_cls, '_hsh_sig', hsh)

            return new_cls

        raise TypeError(f'{cls.__name__}() called without keyword arguments. '
                        'Use keyword arguments only for dynamic enum creation.'
                        )


class BITFIELD(ExtendedEnum, metaclass=BitFieldEnumMeta):
    """# Summary

    Base class for Enums where members are defined via keyword arguments
    to the class definition. The value of each member is the
    provided integer value, LEFT-shifted by its order (index).

    ## Example:
        class MyFlags(OrderedShiftedEnum, F1=1, F2=1, F3=1):
            pass

        MyFlags.F1.value will be 1 (1 << 0)

        MyFlags.F2.value will be 2 (1 << 1)

        MyFlags.F3.value will be 4 (1 << 2)
    """
    __slots__ = ('hsh_sig', 'int_sig', 'bit_length')

    @override
    @classmethod
    def fields(cls) -> Iterable:
        return list(cls.__members__.keys())

    @override
    @classmethod
    def values(cls) -> Iterable:
        return list([v.value for v in cls.__members__.values()])
